import {
    backend,
    javascript,
    typescript,
    html,
    css,
    reactjs,
    tailwind,
    nodejs,
    mongodb,
    git,
    three,
    azure,
    mui,
    vite,
    freelance,
    ak,
    code,
    atom,
    gamedev,
    crypto,
    dalle,
    chatgpt,
    booking,
    gym,
    pinterest,
    github,
    linkedin,
  } from "../assets";
  
  export const navLinks = [
    {
      id: "about",
      title: "About",
    },
    {
      id: "work",
      title: "Work",
    },
    {
      id: "contact",
      title: "Contact",
    },
    {
      id: "linkedin",
      icon: linkedin,
      url: "https://www.linkedin.com/in/akin-gungor"
    },
    {
      id: "GitHub",
      icon: github,
      url: "https://github.com/akngngr"
    },
  ];
  
  const services = [
    {
      title: "Web Developer",
      icon: code,
    },
    {
      title: "React Developer",
      icon: atom,
    },
    {
      title: "Backend Developer",
      icon: backend,
    },
    // {
    //   title: "Game Dev Enthusiast",
    //   icon: gamedev,
    // },
  ];
  
  const technologies = [
    {
      name: "HTML 5",
      icon: html,
    },
    {
      name: "CSS 3",
      icon: css,
    },
    {
      name: "JavaScript",
      icon: javascript,
    },
    {
      name: "TypeScript",
      icon: typescript,
    },
    {
      name: "React JS",
      icon: reactjs,
    },
    {
      name: "vite",
      icon: vite,
    },
    {
      name: "Tailwind CSS",
      icon: tailwind,
    },
    {
      name: "Node JS",
      icon: nodejs,
    },
    {
      name: "MongoDB",
      icon: mongodb,
    },
    {
      name: "Three JS",
      icon: three,
    },
    {
      name: "git",
      icon: git,
    },
    {
      name: "mui",
      icon: mui,
    },
    {
      name: "azure",
      icon: azure,
    },
  ];
  
  const experiences = [
    {
      title: "Sr. Software Support Engineer",
      company_name: "Akumina",
      icon: ak,
      iconBg: "#383E56",
      date: "April 2022 - Present",
      points: [
        "Provide software and developer support for enterprise clients world-wide, install, configure and upgrade Production and Development environments.",
        "Formulate responses to tickets, communicate progress and resolution efficiently in collaboration with End Users, Stakeholders, Developers, Project Managers and Customer Success teams.",
        "Provide training of the software and create documentations for internal and public use.",
        "Communicate across development teams to specifically articulate software bugs, observations, actions and resolutions throughout the technical problem-solving process.",
        "Articulate limitations of the software features to clients, while being resourceful in finding ways to meet project requirements by utilizing the full extent of the software capabilities.",
        "Analyze error logs and performance graphs to troubleshoot software bugs and conduct Root Cause Analysis.",
        "Technologies: HTML5, CSS3, JavaScript, React, Git, Azure"
      ],
    },
    {
      title: "Web Developer",
      company_name: "Freelance",
      icon: freelance,
      iconBg: "#E6DEDD",
      date: "Jan 2018 - Present",
      points: [
        "Develop and maintain web applications using ReactJS, UI libraries and other related development technologies.",
        "Translate web designs into stable and maintainable React components.",
        "Collaborate with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
        "Implement responsive design and ensure cross-browser compatibility.",
        "Participate in code reviews and provide constructive feedback to other developers.",
      ],
    },
  ];
  
  const testimonials = [
    {
      testimonial:
        "",
      name: "",
      designation: "",
      company: "",
      image: "",
    },
    {
      testimonial:
        "",
      name: "",
      designation: "",
      company: "",
      image: "",
    },
    {
      testimonial:
        "",
      name: "",
      designation: "",
      company: "",
      image: "",
    },
  ];
  
  const projects = [
    {
      name: "DALL-E 2.0 Clone",
      description:
        "Web-based platform that allows users to create and post AI images generated by DALL-E Chat GPT engine, providing a social timeline to allow users view and collaborate artwork.",
      tags: [
        {
          name: "react",
          color: "blue-text-gradient",
        },
        {
          name: "mongodb",
          color: "green-text-gradient",
        },
        {
          name: "tailwind",
          color: "pink-text-gradient",
        },
      ],
      image: dalle,
      source_code_link: "https://github.com/akngngr/ai-image-social",
    },
    {
      name: "Chat GPT AI Clone",
      description:
        "Web application that allows users to search for answers to any questions using Chat GPT 3.5 engine.",
      tags: [
        {
          name: "react",
          color: "blue-text-gradient",
        },
        {
          name: "restapi",
          color: "green-text-gradient",
        },
        {
          name: "scss",
          color: "pink-text-gradient",
        },
      ],
      image: chatgpt,
      source_code_link: "https://github.com/akngngr/codex",
    },
    {
      name: "Travel Booking App",
      description:
        "A comprehensive travel booking platform that allows users to book flights, hotels, and rental cars, and offers curated recommendations for popular destinations.",
      tags: [
        {
          name: "nextjs",
          color: "blue-text-gradient",
        },
        {
          name: "supabase",
          color: "green-text-gradient",
        },
        {
          name: "css",
          color: "pink-text-gradient",
        },
      ],
      image: booking,
      source_code_link: "https://github.com/akngngr/booking-app",
    },
    {
      name: "Workout App",
      description:
        "A comprehensive gym exercise platform that allows users to search all kinds of exercises by muscle group, exercise or equipment type.With the functionality to choose exercise categories and specific muscle groups, browse more than one thousand exercises with practical examples, pagination, exercise details, pull related videos from Youtube, display similar exercises, and much more.",
      tags: [
        {
          name: "nextjs",
          color: "blue-text-gradient",
        },
        {
          name: "supabase",
          color: "green-text-gradient",
        },
        {
          name: "css",
          color: "pink-text-gradient",
        },
      ],
      image: gym,
      source_code_link: "https://github.com/akngngr/gym-exercises",
    },
    {
      name: "Crypto Tracker",
      description:
        "View live changes on Crypto.",
      tags: [
        {
          name: "react",
          color: "blue-text-gradient",
        },
        {
          name: "axios",
          color: "green-text-gradient",
        },
        {
          name: "css",
          color: "pink-text-gradient",
        },
      ],
      image: crypto,
      source_code_link: "https://github.com/akngngr/crypto-api-project",
    },
    {
      name: "Pinterest Clone",
      description:
        "A comprehensive travel booking platform that allows users to book flights, hotels, and rental cars, and offers curated recommendations for popular destinations.",
      tags: [
        {
          name: "react",
          color: "blue-text-gradient",
        },
        {
          name: "MUI",
          color: "skyblue-text-gradient",
        },
        {
          name: "axios",
          color: "green-text-gradient",
        },
      ],
      image: pinterest,
      source_code_link: "https://github.com/",
    },
    // {
    //   name: "Weather App",
    //   description:
    //     "A comprehensive travel booking platform that allows users to book flights, hotels, and rental cars, and offers curated recommendations for popular destinations.",
    //   tags: [
    //     {
    //       name: "nextjs",
    //       color: "blue-text-gradient",
    //     },
    //     {
    //       name: "supabase",
    //       color: "green-text-gradient",
    //     },
    //     {
    //       name: "css",
    //       color: "pink-text-gradient",
    //     },
    //   ],
    //   image: tripguide,
    //   source_code_link: "https://github.com/akngngr/live-weather",
    // },
  ];
  
  export { services, technologies, experiences, testimonials, projects };